export const PROVIDERS = {
  openai: {
    name: "OpenAI",
    defaultBaseUrl: "https://api.openai.com/v1",
    chatModels: [
      { id: "gpt-5.4", name: "GPT-5.4", inputPrice: 2.5, outputPrice: 15.0 },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        inputPrice: 0.75,
        outputPrice: 4.5,
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 Nano",
        inputPrice: 0.2,
        outputPrice: 1.25,
      },
      {
        id: "gpt-5-mini-2025-08-07",
        name: "GPT-5 Mini",
        inputPrice: 0.25,
        outputPrice: 2.0,
      },
      {
        id: "gpt-5-nano-2025-08-07",
        name: "GPT-5 Nano",
        inputPrice: 0.05,
        outputPrice: 0.4,
      },
    ],
    ttsModels: [
      { id: "tts-1", name: "TTS-1" },
      { id: "tts-1-hd", name: "TTS-1 HD" },
      { id: "gpt-4o-mini-tts", name: "GPT-4o Mini TTS" },
    ],
    ttsVoices: [
      "alloy",
      "ash",
      "ballad",
      "coral",
      "echo",
      "fable",
      "nova",
      "onyx",
      "sage",
      "shimmer",
    ],
  },
  anthropic: {
    name: "Anthropic",
    defaultBaseUrl: "https://api.anthropic.com",
    chatModels: [
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        inputPrice: 5.0,
        outputPrice: 25.0,
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        inputPrice: 3.0,
        outputPrice: 15.0,
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        inputPrice: 1.0,
        outputPrice: 5.0,
      },
    ],
    ttsModels: [],
    ttsVoices: [],
  },
  google: {
    name: "Google",
    defaultBaseUrl: "https://generativelanguage.googleapis.com",
    chatModels: [
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro",
        inputPrice: 2.0,
        outputPrice: 12.0,
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash",
        inputPrice: 0.75,
        outputPrice: 4.5,
      },
      {
        id: "gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash-Lite",
        inputPrice: 0.25,
        outputPrice: 1.5,
      },
    ],
    ttsModels: [
      { id: "gemini-2.5-flash-preview-tts", name: "Gemini 2.5 Flash TTS" },
      { id: "gemini-2.5-pro-preview-tts", name: "Gemini 2.5 Pro TTS" },
    ],
    ttsVoices: [
      "Zephyr",
      "Puck",
      "Charon",
      "Kore",
      "Fenrir",
      "Leda",
      "Orus",
      "Aoede",
      "Callirrhoe",
      "Autonoe",
      "Enceladus",
      "Iapetus",
      "Umbriel",
      "Algieba",
      "Despina",
      "Erinome",
      "Algenib",
      "Rasalgethi",
      "Laomedeia",
      "Achernar",
      "Alnilam",
      "Schedar",
      "Gacrux",
      "Pulcherrima",
      "Achird",
      "Zubenelgenubi",
      "Vindemiatrix",
      "Sadachbia",
      "Sadaltager",
      "Sulafat",
    ],
  },
};

export const DEFAULT_CHAT_MODEL = "openai/gpt-4o-mini";
export const DEFAULT_TTS_MODEL = "openai/tts-1";
